### ISSUE TITLE
A few suggested changes for uWmiDelphiClass.pas

### ISSUE THREAD

**Issue by tedsmith** [RRUZ/delphi-wmi-class-generator#3]
So get this to compile on Lazarus 1.4.0 and FPC 2.6.4 I had to change a few lines of uWmiDelphiClass.pas:

101 moved 
{$IFDEF WMI_LateBinding}
    FSWbemLocator   : OleVariant;
    //FWMIService     : OleVariant; // commented out and moved:
to line 104:
{$IFDEF FPC}
    FWMIService     : OleVariant; 
   
Line 192:
{$IFDEF WMI_LateBinding}
   property  SWbemLocator  : OleVariant read FSWbemLocator;
   property  WMIService    : OleVariant read FWMIService; // moved to an FPC IFEDF
to
 {$IFDEF WMI_LateBinding}
   property  SWbemLocator  : OleVariant read FSWbemLocator;
   //property  WMIService    : OleVariant read FWMIService;
   {$IFDEF FPC}
   property  WMIService    : OleVariant read FWMIService;
   {$ENDIF}       
   
1169 from
objWbemObjectSet : = FWMIService.ExecQuery( WQL,'WQL',0);  
to
objWbemObjectSet := WmiConnection.FWMIService.ExecQuery( WQL,'WQL',0);

**Comment by RRUZ** [comment]
I just added a sample FPC Console project (https://github.com/RRUZ/delphi-wmi-class-generator/tree/master/Demos/FPC) and works just fine. No changes  to the uWmiDelphiClass unit was required.

**Comment by tedsmith** [comment]
OK RRUZ. That might go some way to explain why the other problem I was having (with regard to zero being returned for everything) is occuring, perhaps. HOwever, I have started again and immitated your uses declaration syntax (I have copied the entire root_WMI folder to my project folder) but could you perhaps help with why my attempt will not compile without these changes? As you can see, if I don't change uWmiDelphiClass, it will not compile. The screenshots show my uses declaration and the compiler error that is thrown for uWmiDelphiClass.pas. 

![1](https://cloud.githubusercontent.com/assets/1560598/8646536/961a7022-2948-11e5-808a-5ca1fda46072.png)
![2](https://cloud.githubusercontent.com/assets/1560598/8646535/9614cad2-2948-11e5-977d-53ac7b8e2c20.png)

**Comment by RRUZ** [comment]
You must use the *uWmiDelphiClass* unit located in the *units* folder (https://github.com/RRUZ/delphi-wmi-class-generator/tree/master/units)

**Comment by tedsmith** [comment]
OK, I get the distinct idea that all my issues are all linked to this same problem, but I think I am about to jump out the window with this! 

So, thanks for pointing that out. I didn't realise there were two uWmiDelphiClass.pas files (one is generated by 'Delphi WMI Class Generator' and is placed with the units in the generated output and then as you point out, there is one in the source code of the project. 

So, I downloaded the entire repoisitory from Github. Placed the folder in my project folder. I then specified the path in my uses section for uWmiDelphiClass.pas as \delphi-wmi-class-generator-master\units. 

And for uSystemConfig_V2_PhyDisk.pas and uSystemConfig_V2_LogDisk.pas, I copied those from the generated units folder of 'Delphi WMI Class Generator' and copied those to the root of my project folder. To be double sure, I also "added them to the project" via Project --> Project Inspector --> Add files. I then tried to compile.

I get the same error as before but on a different line 1571 of uWmiDelphiClass.pas

uWmiDelphiClass.pas(1571,26) Error: Identifier not found "FWMIService"

So, to simplify things, I copied uWmiDelphiClass.pas to the root of my project folder, along with the other two. Tried to compile. Same error.

"No changes to the uWmiDelphiClass unit was required." - I'd love to know what you are doing different to me, because I cannot get this to compile without moving a load of IFDEF directives, and then I don't get valid values returned. 

You did see that I am using Lazarus and Freepascal, and not Delphi? 

![untitled](https://cloud.githubusercontent.com/assets/1560598/8655197/86ba9140-2987-11e5-8b7d-61aa5eef4391.png)
![untitled2](https://cloud.githubusercontent.com/assets/1560598/8655198/86bb42ca-2987-11e5-8400-1d4b72cd36a4.png)

**Comment by tedsmith** [comment]
I have tried again from scratch, and ensured I point my uses to the appropriate pas files. Without making any changes to the unit files, I still get compile problems regarding identifiers. So I have zipped up the sample project you provided in the other issue thread and uploaded it to https://drive.google.com/file/d/0B1celo-GPMLHQkRLajVMZmZfUVU/view?usp=sharing - perhaps you can open it and see if you get the same errors? I don't understand what I am doing wrong and specifically what I am doing differently to yourself.
